#!/bin/bash
# Lmdb v2.0 by Nanoseb
# needs : xmllint xmlstarlet zenity
#man : -i file : shows info about file in a graphical view (zenity) (and write/update info in the bdd)
#      -c file : shows info about file in console (and write/update info in the bdd)
#      file : write info in the bdd
#temp
imdbpage="/tmp/imdbpage"
imdbimage="/tmp/imdbimage"

# cache
imdbbdd="$HOME/.imdbbdd.xml"

imagedl () {
    wget -q -O $imdbimage "$1"
    if [ -s "$imdbimage" ]
    then
        display $imdbimage
        rm "$imdbimage"
    fi
}

convertmins() {
    ((h=${1}/60))
    ((m=${1}%60))
    printf "%01dh%02d" $h $m
}

toxml () {
    sed 's/>/&gt;/g
s/</&lt;/g
s/\"/&quot;/g
s/&/&amps;/g'
}

omdbapi () {
    wget -q -O $imdbpage "http://www.omdbapi.com/?r=XML&plot=full&i=${id}"

    erreur=$(xmllint --xpath "//root/@response" "$imdbpage" | awk -F"\"" '{print $2}')
    image=$(xmllint --xpath "//root/movie/@poster" "$imdbpage" | awk -F"\"" '{print $2}')
    rating=$(xmllint --xpath "//root/movie/@imdbRating" "$imdbpage" | awk -F"\"" '{print $2}')
    plot=$(xmllint --xpath "//root/movie/@plot" "$imdbpage"  | awk -F"\"" '{print $2}')
    title=$(xmllint --xpath "//root/movie/@title" "$imdbpage"  | awk -F"\"" '{print $2}')
    year=$(xmllint --xpath "//root/movie/@year" "$imdbpage" | awk -F"\"" '{print $2}')
    time=$(xmllint --xpath "//root/movie/@runtime" "$imdbpage" | awk -F"\"" '{print $2}' | sed 's/\ //g' | sed 's/min//')
    real=$(xmllint --xpath "//root/movie/@director" "$imdbpage" | awk -F"\"" '{print $2}')
    genre=$(xmllint --xpath "//root/movie/@genre" "$imdbpage" | awk -F"\"" '{print $2}')
    actors=$(xmllint --xpath "//root/movie/@actors" "$imdbpage" | awk -F"\"" '{print $2}')

    rm $imdbpage

}

ecritcache () {
    omdbapi


    if [ "$erreur" = "False" ]
    then
        echo "film non trouvé"
        exit 1
    fi

    if [ -f "$chemin" ]
    then
        if [ -n $(grep "N/A" <<< "$time") ]
        then
            time=$(convertmins "$time")
        fi

        ################ écriture de la BDD ###########################

        sed -i '$d' $imdbbdd
        sed -i '$d' $imdbbdd

        echo -e "<film>
            <id>$id</id>
            <title>$title</title>
            <year>$year</year>
            <time>$time</time>
            <real>$real</real>
            <genre>$genre</genre>
            <actors>$actors</actors>
            <rating>$rating</rating>
            <plot>$plot</plot>
            <image>$image</image>
            <filename>$filename</filename>
            <chemin>$chemin</chemin>
            </film>
            </table>
            </xml>" >> $imdbbdd
        ################################################################
    fi
}


litcache () {
    title=$(xmlstarlet sel -t -m "//film[id='$id']" -v title -n $imdbbdd)
    year=$(xmlstarlet sel -t -m "//film[id='$id']" -v year -n $imdbbdd)
    time=$(xmlstarlet sel -t -m "//film[id='$id']" -v time -n $imdbbdd)
    real=$(xmlstarlet sel -t -m "//film[id='$id']" -v real -n $imdbbdd)
    genre=$(xmlstarlet sel -t -m "//film[id='$id']" -v genre -n $imdbbdd)
    actors=$(xmlstarlet sel -t -m "//film[id='$id']" -v actors -n $imdbbdd)
    rating=$(xmlstarlet sel -t -m "//film[id='$id']" -v rating -n $imdbbdd)
    plot=$(xmlstarlet sel -t -m "//film[id='$id']" -v plot -n $imdbbdd)
    image=$(xmlstarlet sel -t -m "//film[id='$id']" -v image -n $imdbbdd)

    # mise à jour du chemin et du filename dans la bdd
    if [ -f "$chemin" ]
    then
        xmlstarlet ed -u "/xml/table/film[id='$id']/chemin" -v "$chemin" $imdbbdd > $imdbpage
        mv $imdbpage $imdbbdd

        xmlstarlet ed -u "/xml/table/film[id='$id']/filename" -v "$filename" $imdbbdd > $imdbpage
        mv $imdbpage $imdbbdd
    fi
}


if [ $1  = "-a" ]  #argument pour rentrer manuelement l'url de la page imdb
then
    arg="-c"
    id=$(zenity --entry --title "Script LMDb" | awk -F"/" '{print $5}')
    film="$2"
    chemin=$(toxml <<< "$PWD/$(sed 's/^\.\///' <<< "$film")")
    filename=$(basename "$film" | sed 's/\.[^.]*$//' | awk -F"[" '{print $1}' | sed 's/\ $//' | tr "'" " " | toxml)
    xmlstarlet ed -d "/xml/table/film[filename='$filename']" $imdbbdd > $imdbpage
    mv $imdbpage $imdbbdd
    xmlstarlet ed -d "/xml/table/film[id='$id']" $imdbbdd > $imdbpage
    mv $imdbpage $imdbbdd
    ecritcache

else

    if [ -z "$2" ]
    then
        film="$1"
        arg="-m"
    else
        film="$2"
        arg=$1
    fi

    chemin=$(toxml <<< "$PWD/$(sed 's/^\.\///' <<< "$film")")


    filename=$(basename "$film" | sed 's/\.[^.]*$//' | awk -F"[" '{print $1}' | sed 's/\ $//')


    motclef=$(sed 's/\ /\%20/g' <<< "$filename")

    filename=$(tr "'" " " <<< "$filename" | toxml)




    id=$(xmlstarlet sel -t -m "//film[filename='$filename']" -v id -n $imdbbdd)



    if [ -n "$id" ]    # test si le film est en cache
    then

        litcache

    else
        ############### recherche du film sur IMDB ###################


        id=$(curl -s "http://www.imdb.com/find?s=tt&q=$motclef" | grep -m 1 "<a href=\"/title/" | awk -F"/" '{print $3}')

        dejala=$(grep "$id" $imdbbdd)

        if [ -n "$dejala" ]
        then

            litcache

        else
            ecritcache

        fi
    fi


fi


if [ $arg == "-i" ]
then
    if [ -n "$image" ]
    then
        imagedl $image &
    fi
    echo -e "$title ($year) - $time \n de $real \n avec $actors \n $genre \n $rating/10 \n $plot" | zenity --text-info --title="Script LMDb"
    pkill display
else
    if [ $arg == "-c" ]
    then
        echo -e "$title ($year) - $time \n de $real \n avec $actors \n $rating/10 \n $plot"
    fi
fi

exit 0
